name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan:
    name: Terraform Plan (on PR)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3

      # ✅ Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1

      # ✅ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: "1.6.0"

      # ✅ Init
      - name: Terraform Init
        run: terraform init

      # ✅ Plan
      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply (on main)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      # ✅ Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1

      # ✅ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: "1.6.0"

      # ✅ Init
      - name: Terraform Init
        run: terraform init

      # ✅ Plan
      - name: Terraform Plan
        run: terraform plan -out=plan.tfplan

      # ✅ Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve plan.tfplan
