name: Terraform CI/CD
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Plan and Apply
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      # ✅ Setup AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1

      # ✅ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: "1.6.0"

      # ✅ Init
      - name: Terraform Init
        run: terraform init

      # ✅ Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=plan.tfplan

      # ✅ Apply (only when pushed to main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve plan.tfplan
